openapi: 3.0.3
info:
  title: 'hh'
  description: 'Базовый аналог hh'
  version: 1.0.0
servers:
  - url: 'http://127.0.0.1:5000/api/v1/'
tags:
  - name: User
    description: 'Операции, связанными с пользователем'
  - name: Jwt
    description: 'Операции, связанными с jwt'
  - name: Role
    description: 'Операции, связанными с ролями'
  - name: Skills
    description: 'Операции, связанными с навыками'
  - name: Vacancy
    description: 'Операции, связанными с вакансиями'
paths:
  /user:
    post:
      tags:
        - User
      summary: 'Создание пользователя'
      description: 'Отправляем запрос для создания нового пользователя'
      operationId: saveUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#components/schemas/UserCreate"
      responses:
        201:
          description: 'Пользователь успешно создан'
    get:
      security:
        - BearerAuth: [ ]
      tags:
        - User
      summary: 'Получаем пользователя'
      description: 'Отправляем запрос для получения пользователя'
      operationId: getUser
      responses:
        '200':
          description: 'Получение пользователя'
          content:
            application/json:
              schema:
                $ref: "#components/schemas/UserDetail"
  /user/role:
    post:
      security:
        - BearerAuth: [ ]
      tags:
        - User
      summary: 'Устанавливаем роли доступа для пользователя'
      description: 'Отправляем запрос для записи роли'
      operationId: SaveUserRoles
      requestBody:
        content:
          application/json:
            schema:
              properties:
                roles:
                  type: array
                  items:
                    type: integer
      responses:
        '201':
          description: 'Роли успешно добавлены'
  /user/resumes:
    get:
      security:
        - BearerAuth: [ ]
      tags:
        - User
      summary: 'Список всех резюме'
      description: 'Получаем список резюме созданным пользователем'
      operationId: getUserResumes
      responses:
        '200':
          description: 'Список резюме'
          content:
            application/json:
              schema:
                $ref: "#components/schemas/UserResumes"
    post:
      security:
        - BearerAuth: [ ]
      tags:
        - User
      summary: 'Создание резюме'
      description: 'Отправляем запрос для создания нового резюме'
      operationId: SaveUserResumes
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#components/schemas/UserResumeSave"
      responses:
        '201':
          description: 'Резюме создано'
          content:
            application/json:
              schema:
                properties:
                  id:
                    type: integer
                  salary:
                    type: integer
                  title:
                    type: string
                  description:
                    type: string
                  publication_date:
                    type: string
                    format: date-time
  /user/resumes/{resumesId}:
    get:
      security:
        - BearerAuth: [ ]
      tags:
        - User
      summary: 'Информация о резюме'
      description: 'Получить информацию о выбранном резюме пользователя'
      operationId: getUserResumesDetail
      parameters:
        - name: resumesId
          description: 'Идентификатор резюме'
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: 'Сведения о резюме'
          content:
            application/json:
              schema:
                $ref: "#components/schemas/UserResumeDetail"
    put:
      security:
        - BearerAuth: [ ]
      tags:
        - User
      summary: 'Информация о резюме'
      description: 'Получить информацию о выбранном резюме пользователя'
      operationId: putUserResumesDetail
      parameters:
        - name: resumesId
          description: 'Идентификатор резюме'
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#components/schemas/UserResumeSave"
      responses:
        '200':
          description: 'Сведения о резюме'
          content:
            application/json:
              schema:
                $ref: "#components/schemas/UserResumeSave"
    delete:
      security:
        - BearerAuth: [ ]
      tags:
        - User
      summary: 'Удалить резюме'
      description: 'Удалить выбранное резюме'
      operationId: deleteUserResumesDetail
      parameters:
        - name: resumesId
          description: 'Идентификатор резюме'
          in: path
          required: true
      responses:
        '200':
          description: 'Резюме удален'
        '204':
          description: 'Резюме для удоления не найдена'
  /jwt/create:
    post:
      tags:
        - Jwt
      summary: 'Создание токена'
      description: 'Отправляем запрос для создания токена jwt'
      operationId: CreateJwt
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  format: password
      responses:
        '200':
          description: 'Получение jwt токена'
  /jwt/refresh:
    post:
      security:
        - BearerAuth: [ ]
      tags:
        - Jwt
      summary: 'Обновление токена'
      description: 'Отправляем запрос для обновления токена jwt'
      operationId: RefreshJwt
      responses:
        '200':
          description: 'Получение нового jwt токена'
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
  /role:
    get:
      tags:
        - Role
      summary: 'Список всех ролей'
      description: 'Получаем список ролей'
      operationId: getRoles
      responses:
        "200":
          description: 'Список ролей'
          content:
            application/json:
              schema:
                $ref: "#components/schemas/Role"
    post:
      security:
        - BearerAuth: [ ]
      tags:
        - Role
      summary: 'Создание роли'
      description: 'Отправляем запрос для создания новой роли'
      operationId: saveRole
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#components/schemas/RoleDetail"
      responses:
        '201':
          description: 'Роль успешна создана'
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
        '400':
          description: 'Ошибка в создание роли'
  /role/{roleId} :
    get:
      tags:
        - Role
      summary: 'Информация о роли'
      description: 'Получить информацию о выбранной роли'
      operationId: getRole
      parameters:
        - name: roleId
          description: 'Идентификатор роли'
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          description: 'Сведения о роли'
          content:
            application/json:
              schema:
                $ref: "#components/schemas/RoleDetail"
        204:
          description: 'Роль с таким идентификатором id отсутсвует'
    put:
      security:
        - BearerAuth: [ ]
      tags:
        - Role
      summary: 'Обновить роль'
      description: 'Обновить информацию о выбранной роли'
      operationId: updateRole
      parameters:
        - name: roleId
          description: 'Идентификатор роли'
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        content:
           application/json:
             schema:
               $ref: "#components/schemas/RoleDetail"
      responses:
        '200':
          description: 'Роль успешна обновлена'
          content:
            application/json:
              schema:
                properties:
                  id:
                    type: integer
                  name:
                    type: string
        '400':
          description: 'Ошибка в обновлений роли'
    delete:
      security:
        - BearerAuth: [ ]
      tags:
        - Role
      summary: 'Удалить роль'
      description: 'Удалить выбранную роль'
      operationId: deleteRole
      parameters:
        - name: roleId
          description: 'Идентификатор роли'
          in: path
          required: true
      responses:
        '200':
          description: 'Роль удалена'
        '204':
          description: 'Роль для удоления не найдена'
  /skills:
    get:
      tags:
        - Skills
      summary: 'Список всех навыков'
      description: 'Получаем список навыков'
      operationId: getSkills
      responses:
        '200':
          description: 'Список навыков'
          content:
            application/json:
              schema:
                $ref: "#components/schemas/Skills"
    post:
      security:
        - BearerAuth: [ ]
      tags:
        - Skills
      summary: 'Создание навыков'
      description: 'Отправляем запрос для создания нового навыка'
      operationId: saveSkill
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#components/schemas/SkillDetail"
      responses:
        '201':
          description: 'Навык успешно создан'
          content:
             application/json:
               schema:
                 type: object
                 properties:
                   id:
                    type: integer
                   name:
                    type: string
        '400':
             description: 'Ошибка в создание навыка'
  /skills/{skillId}:
    get:
      tags:
        - Skills
      summary: 'Информация о навыке'
      description: 'Получить информацию о выбранном навыке'
      operationId: getSkill
      parameters:
        - name: skillId
          description: 'Идентификатор навыка'
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: 'Сведения о навыках'
          content:
            application/json:
              schema:
                $ref: "#components/schemas/SkillDetail"
        '204':
          description: 'Навык с таким идентификатором id отсутсвует'
    put:
      security:
        - BearerAuth: [ ]
      tags:
        - Skills
      summary: 'Обновить навык'
      description: 'Обновить информацию о выбранном навыке'
      operationId: updateSkill
      parameters:
        - name: skillId
          description: 'Идентификатор навыка'
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#components/schemas/SkillDetail"
      responses:
        '200':
          description: 'Роль успешна обновлена'
          content:
            application/json:
              schema:
                properties:
                  id:
                    type: integer
                  name:
                    type: string
        '400':
          description: 'Ошибка в обновление навыка'
    delete:
      security:
        - BearerAuth: [ ]
      tags:
        - Skills
      summary: 'Удалить роль'
      description: 'Удалить выбранную роль'
      operationId: deleteSkill
      parameters:
        - name: skillId
          description: 'Идентификатор навыка'
          in: path
          required: true
      responses:
        '200':
          description: 'Навык удален'
        '204':
          description: 'Навык для удоления не найден'


components:
  schemas:
    Role:
      type: array
      items:
        type: object
        properties:
          id:
            type: integer
          name:
            type: string
    RoleDetail:
      type: object
      properties:
        name:
          type: string
    Skills:
      type: array
      items:
        type: object
        properties:
          id:
            type: integer
          name:
            type: string
    SkillDetail:
      type: object
      properties:
        name:
          type: string
    Vacancy:
      type: array
      items:
        type: object
        properties:
          id:
            type: integer
          name:
            type: string
    VacancyDetail:
      type: object
      properties:
        name:
          type: string
    UserCreate:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
        first_name:
          type: string
        last_name:
          type: string
        phone:
          type: string
    UserDetail:
      type: object
      properties:
        id:
          type: integer
        first_name:
          type: string
        last_name:
          type: string
        email:
          type: string
        phone:
          type: string
        roles:
          type: array
          items:
            properties:
              id:
                type: integer
              name:
                type: string
    UserResumes:
      type: array
      items:
        properties:
          id:
            type: integer
          salary:
            type: integer
          title:
            type: string
          description:
            type: string
          publication_date:
            type: string
            format: date-time

    UserResumeDetail:
      type: object
      properties:
        salary:
          type: integer
        title:
          type: string
        description:
          type: string
        publication_date:
          type: string
          format: date-time
    UserResumeSave:
      type: object
      properties:
        salary:
          type: integer
        title:
          type: string
        description:
          type: string


  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT